# Generated by Django 2.0 on 2018-04-22 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_auto_20180422_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.CharField(choices=[(None, 'Click here to select the group'), ('BC', 'Brisbane Central Scout')], default='None', max_length=27)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='scout_group',
            name='scout_username',
        ),
        migrations.DeleteModel(
            name='Scout_Group',
        ),
    ]
