# Generated by Django 2.0 on 2018-04-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180422_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoutgroup',
            old_name='Group',
            new_name='Troop',
        ),
    ]
