# Generated by Django 2.0 on 2018-04-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180422_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutgroup',
            name='Troop',
            field=models.SlugField(choices=[(None, 'Click here to select the group'), ('BC', 'Brisbane Central Scout')], default='None', max_length=27),
        ),
    ]
