# Generated by Django 2.0 on 2018-06-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180422_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutgroup',
            name='Troop',
            field=models.SlugField(choices=[(None, 'Click here to select the group'), ('BC', 'Brisbane Central Scout'), ('Admin', 'N/A')], default='None', max_length=27),
        ),
    ]
