# Generated by Django 2.0.7 on 2018-08-11 00:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troop', models.SlugField(choices=[(None, 'Click here to select the group'), ('BC', 'Brisbane Central Scout'), ('NA', 'Admin'), ('NG', 'New Group'), ('2V', '2nd Valley'), ('KSG', 'Koondall Scout Group'), ('RSG', 'Roomal Scout Group'), ('NFS', 'New Farm Scout Group'), ('GTS', 'Gregory Terrace Scouts'), ('BNG', 'Brisbane New Group'), ('NG2', 'New Group 2'), ('AG2', 'Another Group 2'), ('FG1', 'Final Group 1'), ('NTS', 'Nothing'), ('AT3', 'Another Troop'), ('TSG2', 'Another Test Group'), ('TS3', 'Test Group 3'), ('TG4', 'Test Group 4'), ('TG5', 'Test Group 5'), ('TG6', 'Test Group 6'), ('TG7', 'Test Group 7'), ('TG8', 'Test Group 8'), ('TG9', 'Test Group 9'), ('TGs1', 'Test Groups 1'), ('TGs2', 'Test Groups 2'), ('TGs3', 'Test Groups 3'), ('TGs4', 'Test Groups 4'), ('TGs5', 'Test Groups 5'), ('TGs6', 'Test Groups 6'), ('TGs7', 'Test Groups 7'), ('TGs9', 'Test Groups 9'), ('FTG', 'Final Test Group'), ('TsG1', 'Tests G 1'), ('TG1', 'T G 1'), ('TG2', 'T G 2'), ('TG3', 'T G 3'), ('TG4', 'T G 4'), ('TG5', 'T G 5'), ('FTG2', 'Final Tests Group 2'), ('TsGs', 'Testing Group'), ('TsGs2', 'Testings'), ('NT1', 'New Troop 1'), ('AG3', 'Another Group 3'), ('AnG', 'A new Group')], default='None', max_length=27)),
                ('role', models.CharField(choices=[('Leader', 'Leader'), ('Scout', 'Scout')], default='Scout', max_length=7)),
                ('date_of_birth', models.DateField(default=datetime.date.today, null=True)),
                ('scout_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
