# Generated by Django 2.0.7 on 2018-09-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='troop',
            field=models.SlugField(choices=[(None, 'Click here to select the group')], default='None', max_length=27),
        ),
    ]
