# Generated by Django 2.0.7 on 2018-08-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprecord',
            name='subscription',
            field=models.CharField(choices=[('Basic', 'Premium'), ('Premium', 'Premium')], default='Basic', max_length=8),
        ),
    ]
