# Generated by Django 2.1.3 on 2018-12-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='troop',
            field=models.SlugField(choices=[(None, 'Click here to select the group'), ('NA', 'Admin'), ('TG1', 'Test Group 1'), ('TG2', 'Test Group 2'), ('TG5', 'Test Group 5'), ('TG4', 'Test Group 4'), ('AVC', 'ACVBF'), ('TG6', 'Test Group 6'), ('TG8', 'Test Group 8'), ('TG9', 'Test Group 9'), ('TG10', 'Test Group 10'), ('TG11', 'Test Group 11'), ('TG12', 'Test Group 12'), ('TG13', 'Test Group 13'), ('TG14', 'Test Group 14'), ('TG15', 'Test Group 15'), ('TG16', 'Test Group 16'), ('TG17', 'Test Group 17'), ('TG18', 'Test Group 18'), ('TG19', 'Test Group 19'), ('TG20', 'Test Group 20'), ('TG21', 'Test Group 21'), ('TG22', 'Test Group 22'), ('TG23', 'Test Group 23'), ('TG24', 'Test Group 24'), ('TG25', 'Test Group 25'), ('N/A2', 'Admin2'), ('TG26', 'Test Group 26'), ('N/A3', 'Admin3'), ('TG28', 'Test Group 28'), ('TG29', 'Test Group 29'), ('troop', 'Admin'), ('TG30', 'Test Group 30')], default='None', max_length=27),
        ),
    ]
