# Generated by Django 2.1.3 on 2018-12-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_secondary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='troop',
            field=models.SlugField(choices=[(None, 'Click here to select the group'), ('NA', 'Admin')], default='None', max_length=27),
        ),
    ]
