# Generated by Django 2.0.7 on 2018-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_grouprecord_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprecord',
            name='subscription',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], default='Basic', max_length=8),
        ),
    ]
