# Generated by Django 2.1.3 on 2018-11-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181108_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='troop',
            field=models.SlugField(choices=[(None, 'Click here to select the group')], default='None', max_length=27),
        ),
    ]
