# Generated by Django 2.1.3 on 2018-12-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_grouprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='troop',
            field=models.SlugField(choices=[('NA', 'Admin')], default='None', max_length=27),
        ),
    ]
