# Generated by Django 2.1.3 on 2018-12-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181208_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='troop',
            field=models.SlugField(choices=[(None, 'Click here to select the group'), ('NA', 'Admin'), ('TG1', 'Test Group 1'), ('TG2', 'Test Group 2'), ('TG5', 'Test Group 5'), ('TG4', 'Test Group 4'), ('AVC', 'ACVBF')], default='None', max_length=27),
        ),
    ]
