# Generated by Django 2.0.7 on 2018-08-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180811_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='troop',
            field=models.SlugField(choices=[(None, 'Click here to select the group'), ('BC', 'Brisbane Central Scout'), ('NA', 'Admin'), ('NG', 'New Group'), ('NG2', 'New Group 2'), ('NTS', 'Nothing'), ('ET', 'EmailTest'), ('ETs', 'EmailTesting'), ('PT', 'PlanTest'), ('ST1', 'StripeTest1'), ('St2', 'StripeTest2'), ('St3', 'StripeTest3')], default='None', max_length=27),
        ),
    ]
