# Generated by Django 2.1.3 on 2018-12-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181208_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
