# Generated by Django 2.1.3 on 2018-11-08 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pioneer_Badge', models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Emergencies', 'Emergencies'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Patrol Activity', 'Patrol Activity'), ('Chord', 'Chord'), ('Target Badge', 'Target Badge')], default='None', max_length=16)),
                ('Explorer_Badge', models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Emergencies', 'Emergencies'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Patrol Activity', 'Patrol Activity'), ('Chord', 'Chord'), ('Target Badge', 'Target Badge')], default='None', max_length=16)),
                ('Adventurer_Badge', models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Emergencies', 'Emergencies'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Patrol Activity', 'Patrol Activity'), ('Chord', 'Chord'), ('Target Badge', 'Target Badge')], default='None', max_length=16)),
                ('Proficiency_Badge', models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Agriculture', 'Agriculture'), ('Animal Keeper', 'Animal Keeper'), ('Anthropology', 'Anthropology'), ('Art', 'Art'), ('Astronomy', 'Astronomy'), ('Bushcraft', 'Bushcraft'), ('Caving', 'Caving'), ('Collector', 'Collector'), ('Commerce', 'Commerce'), ('Communication', 'Communication'), ('Community', 'Community'), ('Craft', 'Craft'), ('Crime Prevention', 'Crime Prevention'), ('Entertainer', 'Entertainer'), ('Fire Awareness', 'Fire Awareness'), ('Heritage', 'Heritage'), ('Induvidual Sportsman', 'Induvidual Sportsman'), ('Literacy Arts', 'Literacy Arts'), ('Modeller', 'Modeller'), ('Multi-Media', 'Multi-Media'), ('Music', 'Music'), ('Outdoor', 'Outdoor'), ('Performing Arts', 'Performing Arts'), ('Rock Climbing', 'Rock Climbing'), ('Science', 'Science'), ('Team Sports', 'Team Sports'), ('Technology', 'Technology'), ('Trades', 'Trades'), ('World Scouting', 'World Scouting')], default='None', max_length=22)),
                ('Other_Badge', models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Amateur Radio Operator', 'Amateur Radio Operator'), ('Anchor', 'Anchor'), ('Deaf Sign Language', 'Deaf Sign Language'), ('Faith Awareness', 'Faith Awareness'), ('First Aid/Life Saving', 'First Aid/Life Saving'), ('Landcare', 'Landcare'), ('Language Emblem', 'Language Emblem'), ('Their Service - Our Heritage', 'Their Service - Our Heritage'), ('World Scout Environment', 'World Scout Environment'), ('ASM', 'ASM'), ('Leadership', 'Leadership')], default='None', max_length=27)),
                ('date', models.DateTimeField(auto_now=True)),
                ('scout_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
