# Generated by Django 2.0 on 2018-04-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfSelectedScouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_scouts', models.SmallIntegerField()),
            ],
        ),
    ]
