# Generated by Django 2.0 on 2018-04-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0002_numberofselectedscouts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberOfSelectedScouts',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='post',
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='Adventurer_Badge',
            field=models.CharField(choices=[('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Chord', 'Chord')], default='Campcraft', max_length=2),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='Explorer_Badge',
            field=models.CharField(choices=[('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Chord', 'Chord')], default='Campcraft', max_length=2),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='Pioneer_Badge',
            field=models.CharField(choices=[('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Chord', 'Chord')], default='Campcraft', max_length=2),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='Proficiency_Badge',
            field=models.CharField(choices=[('Abseiling', 'Abseiling'), ('Agriculture', 'Agriculture'), ('Animal Keeper', 'Animal Keeper'), ('Anthropology', 'Anthropology'), ('Art', 'Art'), ('Astronomy', 'Astronomy'), ('Bushcraft', 'Bushcraft'), ('Caving', 'Caving'), ('Collector', 'Collector'), ('Commerce', 'Commerce'), ('Communication', 'Communication'), ('Community', 'Community'), ('Craft', 'Craft'), ('Crime Prevention', 'Crime Prevention'), ('Entertainer', 'Entertainer'), ('Fire_Awareness', 'Fire Awareness'), ('Heritage', 'Heritage'), ('Induvidual Sportsman', 'Induvidual Sportsman'), ('IT', 'I.T.'), ('Literacy Arts', 'Literacy Arts'), ('Modeller', 'Modeller'), ('Multi-Media', 'Multi-Media'), ('Music', 'Music'), ('Outdoor', 'Outdoor'), ('Performing Arts', 'Performing Arts'), ('Rock Climbing', 'Rock Climbing'), ('Science', 'Science'), ('Team Sports', 'Team Sports'), ('Technology', 'Technology'), ('Trades', 'Trades'), ('World Scouting', 'World Scouting')], default='Abseiling', max_length=2),
        ),
    ]
