# Generated by Django 2.0 on 2018-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0010_auto_20180414_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutdata',
            name='Adventurer_Badge',
            field=models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Emergencies', 'Emergencies'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Patrol Activity', 'Patrol Activity'), ('Chord', 'Chord'), ('Target Badge', 'Target Badge')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='scoutdata',
            name='Explorer_Badge',
            field=models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Emergencies', 'Emergencies'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Patrol Activity', 'Patrol Activity'), ('Chord', 'Chord'), ('Target Badge', 'Target Badge')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='scoutdata',
            name='Other_Badge',
            field=models.CharField(blank=True, default='None', max_length=21),
        ),
        migrations.AlterField(
            model_name='scoutdata',
            name='Pioneer_Badge',
            field=models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Campcraft', 'Campcraft'), ('Citizenship', 'Citizenship'), ('Air Activities', 'Air Activities'), ('Construction', 'Construction'), ('Environment', 'Environment'), ('Emergencies', 'Emergencies'), ('Water Activities', 'Water Activities'), ('Water Safety', 'Water Safety'), ('Target Badge', 'Target Badge'), ('Patrol Activity', 'Patrol Activity'), ('Chord', 'Chord'), ('Target Badge', 'Target Badge')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='scoutdata',
            name='Proficiency_Badge',
            field=models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Agriculture', 'Agriculture'), ('Animal Keeper', 'Animal Keeper'), ('Anthropology', 'Anthropology'), ('Art', 'Art'), ('Astronomy', 'Astronomy'), ('Bushcraft', 'Bushcraft'), ('Caving', 'Caving'), ('Collector', 'Collector'), ('Commerce', 'Commerce'), ('Communication', 'Communication'), ('Community', 'Community'), ('Craft', 'Craft'), ('Crime Prevention', 'Crime Prevention'), ('Entertainer', 'Entertainer'), ('Fire Awareness', 'Fire Awareness'), ('Heritage', 'Heritage'), ('Induvidual Sportsman', 'Induvidual Sportsman'), ('Literacy Arts', 'Literacy Arts'), ('Modeller', 'Modeller'), ('Multi-Media', 'Multi-Media'), ('Music', 'Music'), ('Outdoor', 'Outdoor'), ('Performing Arts', 'Performing Arts'), ('Rock Climbing', 'Rock Climbing'), ('Science', 'Science'), ('Team Sports', 'Team Sports'), ('Technology', 'Technology'), ('Trades', 'Trades'), ('World Scouting', 'World Scouting')], default='None', max_length=22),
        ),
    ]
