# Generated by Django 2.0 on 2018-04-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0011_auto_20180414_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutdata',
            name='Other_Badge',
            field=models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Landcare', 'Landcare'), ('Language Emblem', 'Language Emblem'), ('World Conservation', 'World Conservation'), ('First Aid/Life Saving', 'First Aid/Life Saving'), ('Their Service', 'Their Service'), ('World Scout Environment', 'World Scout Environment'), ('ASM', 'ASM')], default='None', max_length=23),
        ),
    ]
