# Generated by Django 2.0 on 2018-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0012_auto_20180414_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutdata',
            name='Other_Badge',
            field=models.CharField(blank=True, choices=[(None, 'Click here to select the badge'), ('Amateur Radio Operator', 'Amateur Radio Operator'), ('Anchor', 'Anchor'), ('Deaf Sign Language', 'Deaf Sign Language'), ('Faith Awareness', 'Faith Awareness'), ('First Aid/Life Saving', 'First Aid/Life Saving'), ('Landcare', 'Landcare'), ('Language Emblem', 'Language Emblem'), ('Their Service - Our Heritage', 'Their Service - Our Heritage'), ('World Scout Environment', 'World Scout Environment'), ('ASM', 'ASM'), ('Leadership', 'Leadership')], default='None', max_length=27),
        ),
    ]
