# Generated by Django 2.0 on 2018-06-03 03:38

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('leaders', '0013_auto_20180414_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtered_Scouts',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='scoutdata',
            name='scout_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaders.Filtered_Scouts'),
        ),
    ]
