# Generated by Django 2.0 on 2018-06-03 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0014_auto_20180603_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filtered_Scouts',
        ),
        migrations.AlterField(
            model_name='scoutdata',
            name='scout_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
